name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código del repositorio
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Instala Java 17 (evita el error UnsupportedClassVersionError)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. (Opcional) Construir o instalar dependencias antes del análisis
      #    Ajusta esto a tu tecnología (Maven, npm, dotnet, Python, etc.)
      - name: Build
        run: |
          echo "Aquí iría el comando de compilación o instalación de dependencias."
          # Ejemplo (Maven/Java): mvn clean install
          # Ejemplo (Node.js): npm install && npm run build
          # Ejemplo (Python): pip install -r requirements.txt
          # Si no hace falta compilar, déjalo así.

      # 4. Análisis con SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        with:
          args: >
            -Dsonar.projectKey=juan-construsoft_sonar-practicas
            -Dsonar.organization=juan-construsoft
            -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
