name: Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Build (opcional o vacío si no es necesario)
      - name: Build
        run: echo "No build needed"

      # 3. Escanear con SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        with:
          args: >
            -Dsonar.projectKey=juan-construsoft_sonar-practicas
            -Dsonar.organization=juan-construsoft
            -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
